### ISSUE TITLE
Выбор спрайта ячейки

### ISSUE THREAD

**Issue by Kinrany** [Kinrany/ConnectFourXNA#5]
Сделать систему управления спрайтами ячеек

*TO DO: Create a system to assign right sprite for diffrent state of cell using "fileName" variable instead of "empty" string.*

**Comment by Kinrany** [comment]
Перетащил хранение спрайтов в отдельный класс, каждому типу ячейки соответствует один инстанс.

**Comment by shevtsov200** [comment]
По-моему, это можно одним методом с помощью кэйсов сделать.

**Comment by Kinrany** [comment]
Как?

**Comment by shevtsov200** [comment]
Вместо класса Cellimage в методе Cell.Draw добавить такое:
            string fileName = "";

            switch (state)
            {
                case 0:
                    fileName = "empty";
                    break;
                case 1:
                    fileName = "red";
                    break;
                case 2:
                    fileName = "black";
                    break;
            }
Сейчас разберусь, как твои изменения к себе подключить и попробую заработает ли кейсами.

**Comment by shevtsov200** [comment]
Попробовал, вроде, работает. И теперь достаточно, в зависимости от условия, менять state на ноль, один или два в апдейте, и фишка будет меняться.

**Comment by Kinrany** [comment]
Ты при каждой отрисовке загружаешь текстуру. Для изменения состояния фишки вместо всего этого достаточно сделать публичный cell.State и изменять состояние в Update одной строчкой.

**Comment by Kinrany** [comment]
Алсо, switch-case рекомендуют заменять паттернами, а вместо магических чисел лучше enum использовать

**Comment by shevtsov200** [comment]
Я не знал про enum, да, надо будет сделать. А что за паттерны?

**Comment by Kinrany** [comment]
https://ru.wikipedia.org/wiki/Design_Patterns - каноничная книга по паттернам
В двух словах, выбор ветки скрывается уже готовыми механизмами языка. Например, вместо 
```
void Main() {
    // ...
    switch (x) {
    case 0:
        foo0();
        break;
    case 1:
        foo1();
        break;
    }
}
```
писать
```
class AbstractBar {
    public abstract void foo() {}
}
class Bar1 : AbstractBar {
    public override void foo() { 
        // Herp
    }
}
class Bar2 : AbstractBar {
    public override void foo() { 
        // Derp
    }
}

void Main() {
    // ...
    AbstractBar bar;
    // ...
    bar.foo();
}
```

**Comment by shevtsov200** [comment]
Кажется, теперь понял.

**Comment by shevtsov200** [comment]
Пытался сделать выбор ячейки и столкнулся с проблемой:
В XNA проверяют, на какую ячейку нажимают мышкой, используя метод drawRectangle.Contains(mouseState.X, mouseState.Y). А у нас нет drawRectangle нигде, кроме CellImage.Draw, где он создаётся там же, где используется для отрисовки.

**Comment by Kinrany** [comment]
Так-то нам нужен выбор колонок, а не ячеек. Можно каждый клик мыши передавать в board, а там уже искать, к какой колонке он относится. Как-то так:
```
class Board {
    // ...
    public void Mouse(MouseState mouseState) {
        for (int column = 0; column < _columnNumber; ++column) {
            var drawRectangle = new Rectangle(_tileWidth * column, 0, _tileWidth, _tileHeight * _rowNumber);
            if (drawRectangle.Contains(mouseState.X, mouseState.Y)) {
                addTokenToColumn(currentToken, column);
                break;
            }
        }
    }
```

**Comment by shevtsov200** [comment]
А почему у нас нет нормального drawRectangle?

**Comment by shevtsov200** [comment]
Где тебе лучше писать, здесь или в стиме?

**Comment by Kinrany** [comment]
Здесь лучше, вдруг кто-то читать будет.
drawRectangle - это же просто название локальной переменной. Она может быть в разных местах независимо объявлена.
